# Generated by Django 4.2.20 on 2025-04-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("link", models.URLField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("source", models.CharField(max_length=50)),
            ],
        ),
    ]
