# Generated by Django 4.2.20 on 2025-04-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="link",
            field=models.URLField(max_length=1000),
        ),
    ]
