position_map = {
        '백': 'backend',
        '백엔드': 'backend',
        '백엔드개발자': 'backend',
        'backend': 'backend',
        'back': 'backend',
        'back-end': 'backend',
        'node': 'backend',
        'nodejs': 'backend',
        'django': 'backend',
        'flask': 'backend',
        'fastapi': 'backend',
        'nest': 'backend',
        'nestjs': 'backend',
        'spring': 'backend',
        'java': 'backend',
        'golang': 'backend',
        'go': 'backend',
        'kotlin': 'backend',
        'php': 'backend',
        '.net': 'backend',
        'ruby': 'backend',
        'ruby on rails': 'backend',
        '프론트': 'frontend',
        '프론트개발자': 'frontend',
        '프론트엔드': 'frontend',
        'front': 'frontend',
        '프론트엔지니어': 'frontend',
        '프런트엔드': 'frontend',
        'front-end': 'frontend',
        'frontend': 'frontend',
        'react': 'frontend',
        'react.js': 'frontend',
        'vue': 'frontend',
        'vue.js': 'frontend',
        'angular': 'frontend',
        'typescript': 'frontend',
        'html': 'frontend',
        'css': 'frontend',
        'javascript': 'frontend',
        'js': 'frontend',
        'nextjs': 'frontend',
        'next': 'frontend',
        '유니티': 'unity',
        'unity': 'unity',
        '유니티개발자': 'unity',
        '운영': '운영',
        '매니저': '운영',
        '데이터': 'Data',
        'data': 'Data',
        '빅데이터': 'Data',
        '관리': '관리',
        '웹개발자': 'web',
        '웹개발': 'web',
        '웹': 'web',
        'web': 'web',
        'ai': 'AI',
        '인공지능': 'AI',
        '인공': 'AI',
        '블록체인': 'Blockchain',
        '블록': 'Blockchain',
        'blockchain': 'Blockchain',
        '하드웨어': 'hardware',
        'hardware': 'hardware',
        '데브옵스': 'Devops',
        '브옵스': 'Devops',
        'devops': 'Devops',
        'ios': 'App',
        'android': 'App',
        '앱개발': 'App',
        '앱': 'App',
        '안드로이드': 'App',
        'flutter': 'App',
        'reactnative': 'App',
        'react native': 'App',
        '스위프트': 'App',
        'swift': 'App',
        'kotlin': 'App',
        'java(android)': 'App',
        'sre': 'SRE',
        '컨설턴트': '컨설턴트',
        '서버개발자': 'Server',
        '서버개발': 'Server',
        '서버': 'Server',
        'server': 'Server',
        '풀스택': 'fullstack',
        '풀스택개발자': 'fullstack',
        '풀스택엔지니어': 'fullstack',
        'fullstack': 'fullstack',
        'full-stack': 'fullstack',
        'pytorch': 'AI',
        'tensorflow': 'AI',
        '머신러닝': 'AI',
        '딥러닝': 'AI',
        'machine learning': 'AI',
        'deep learning': 'AI',
        '데이터사이언티스트': 'Data',
        '데이터사이언스': 'Data',
        'data scientist': 'Data',
        '데이터분석': 'Data',
        '데이터엔지니어': 'Data',
        '데이터분석가': 'Data',
        'ci': 'Devops',
        'cd': 'Devops',
        'jenkins': 'Devops',
        'kubernetes': 'Devops',
        'docker': 'Devops',
        '인프라': 'Devops',
        'monitoring': 'Devops',
        'full': 'fullstack',
        'cloud':'cloud',
        '클라우드':'cloud',
        'aws':'cloud',
        'gcp':'cloud',
        'azure':'cloud',
        '아마존': 'cloud',
        '애저': 'cloud',
        '신입': '주니어',
        '주니어': '주니어',
        'junior': '주니어',
        '경력': '시니어',
        '시니어': '시니어',
        'Senior': '시니어',
        '팀장': '시니어'
    }

filter_words = [
    '개발자', '채용', '개발', '엔드', '년', '이상', '팀', '급', '기업', '직',
    '모집', '2025', '마', '사업', '글로벌', '2025년', '기술', '공고', '그룹',
    '정보', '엠', '가능', '부문', '담당', '티', '전문', '상반기', '인재', '차',
    '터', '상장사', '부문별', '상장', '본사', '엔지니어', '담당자'
]
